Validate downloaded file. IPs have to be 0.0.0.0|127.0.0.1|255.255.255.255

diff --git a/scripts/etc/cron.weekly/hosts-update b/scripts/etc/cron.weekly/hosts-update
--- a/scripts/etc/cron.weekly/hosts-update
+++ b/scripts/etc/cron.weekly/hosts-update
@@ -1,6 +1,13 @@
 #!/bin/bash
-wget -O /tmp/hosts-zero http://someonewhocares.org/hosts/zero/hosts
+BL_FILE=/tmp/hosts-zero
+BL_URL=http://someonewhocares.org/hosts/zero/hosts
+wget -O ${BL_FILE} ${BL_URL}
 if [[ 0 -eq $? && -f /etc/hosts-original ]]; then
+    INVALID=$(egrep '^[ ]*[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' ${BL_FILE} | egrep -v '(0\.0\.0\.0|127\.0\.0\.1|255\.255\.255\.255)' | wc -l)
+    if [ ${INVALID} -ne 0 ]; then
+        /usr/bin/logger -p 'cron.err' 'Update of hosts file failed. Unknown IPs found.'
+        exit 1
+    fi
     /usr/bin/logger -p 'cron.info' 'Updating hosts file with http://someonewhocares.org/hosts/zero/hosts'
     cat /etc/hosts-original /tmp/hosts-zero > /etc/hosts
     rm /tmp/hosts-zero
